### ISSUE TITLE
BUG: does not build on ubuntu 12.04 LTS server with opal-dev and ptlib-dev installed.

### ISSUE THREAD

**Issue by aftnix** [tmakkonen/sipcmd#1]
Platform:

```
arif@khost:~/sipcmd$ uname -ar
Linux khost 3.2.0-32-generic #51 SMP Mon Oct 8 18:50:35 BDT 2012 x86_64 x86_64 x86_64    
GNU/Linux
```

Libopal version:

```
 libopal-dev    3.10.2~dfsg-0u OPAL library header files
```

LIbpt version

```
 libpt-dev      2.10.2~dfsg-0u Portable Tools Library development files
```

g++ version:

```
g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
```

clang++ version:

```
clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
```

g++ "make" output:

``` make
g++ -c -Wall src/main.cpp -o src/main.o -I/usr/include/opal -I/usr/include/ptlib -Isrc/ -g -DDEBUG
In file included from src/state.h:26:0,
                 from src/main.cpp:26:
src/channels.h: In constructor âTestChannel::TestChannel(OpalConnection&, TestChanAudio&)â:
src/channels.h:112:35: error: cast from âTestChannel*â to âunsigned intâ loses precision [-fpermissive]
src/channels.h: In destructor âvirtual TestChannel::~TestChannel()â:
src/channels.h:116:59: error: cast from âTestChannel*â to âunsigned intâ loses precision [-fpermissive]
src/main.cpp: In member function âbool Manager::SendDTMF(const PString&)â:
src/main.cpp:454:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
src/main.cpp:467:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
src/main.cpp: In member function âvoid RTPSession::SelectAudioFormat(RTPSession::Payload)â:
src/main.cpp:486:28: warning: unused variable âfmtâ [-Wunused-variable]
/usr/include/opal/opal/mediatype.h: At global scope:
/usr/include/opal/opal/mediatype.h:328:1: warning: âPFactoryLoader::T38PseudoRTP_Handler_loaderâ defined but not used [-Wunused-variable]
/usr/include/opal/rtp/rtp.h:1328:1: warning: âPFactoryLoader::RTP_Encoding_loaderâ defined but not used [-Wunused-variable]
/usr/include/opal/opal/pres_ent.h:717:1: warning: âPFactoryLoader::SIP_Presentity_loaderâ defined but not used [-Wunused-variable]
/usr/include/opal/opal/recording.h:194:1: warning: âPFactoryLoader::OpalWAVRecordManager_loaderâ defined but not used [-Wunused-variable]
/usr/include/opal/h323/h235auth.h:228:1: warning: âPFactoryLoader::H235AuthSimpleMD5_loaderâ defined but not used [-Wunused-variable]
/usr/include/opal/h323/h235auth.h:269:1: warning: âPFactoryLoader::H235AuthCAT_loaderâ defined but not used [-Wunused-variable]
/usr/include/opal/h323/h235auth.h:310:1: warning: âPFactoryLoader::H235AuthProcedure1_loaderâ defined but not used [-Wunused-variable]
make: *** [src/main.o] Error 1
```

 clang++ make output: (Too long to post the whole thing:))

``` make
994 warnings and 2 errors generated.
make: *** [src/main.o] Error 1
```
